endpoint = https://demo.reportportal.io
project = default_personal

api_key = VikN-Api_zgwrtDTSRE-cllQMRbmTCQ85HnDZ3kWrfGEpGyiMRc4VZtbSr0Wm2z3o6OZNDirJ
api_version = /api/v1

browser = chrome
headless = false
tor = false
timeout = 30000

login = default
password = 1q2w3e
