endpoint = https://demo.reportportal.io
launch = Java launch
project = default_personal

api.key = rp-test_PxS6WrN7ToS8B5qM6cgc3n8WYt8AUmJnH2Ca022mkhhT3bzmziypGNh_r_4FYfcx
api.version = /api/v1

browser = chrome
headless = false
tor = false
timeout = 30000

login = default
password = 1q2w3e
